# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14FACK9sRq6Q7S6OgWf9Ye717WzWKIrH9
"""

import pickle

model = pickle.load(open("titanic_random_forest.pkl", "rb"))

print("Model loaded successfully")

import numpy as np

# Example passenger
data = np.array([[3, 0, 22, 1, 0, 7.25, 0]])

prediction = model.predict(data)

if prediction[0] == 1:
    print("Passenger Survived")
else:
    print("Passenger Did Not Survive")

def predict_survival(pclass, sex, age, sibsp, parch, fare, embarked):

    model = pickle.load(open("titanic_random_forest.pkl", "rb"))

    data = [[pclass, sex, age, sibsp, parch, fare, embarked]]

    prediction = model.predict(data)

    return prediction[0]


result = predict_survival(3,0,22,1,0,7.25,0)

print("Prediction:", result)

